// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGKLbwUcJaxaTTqbRTF1hmms7Y3XSwpc',
    appId: '1:1061975495730:web:0522f9add5508b326e182b',
    messagingSenderId: '1061975495730',
    projectId: 'smartclass-35336',
    authDomain: 'smartclass-35336.firebaseapp.com',
    storageBucket: 'smartclass-35336.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjiTF9H_Z_yaMf0vU2wo6_Zdavz5qDa0',
    appId: '1:1061975495730:android:eab69435ccd617046e182b',
    messagingSenderId: '1061975495730',
    projectId: 'smartclass-35336',
    storageBucket: 'smartclass-35336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdH_wn6ViCDAYPawuCH-jtJeeNsIAS5bY',
    appId: '1:1061975495730:ios:04c8eed41efb74b76e182b',
    messagingSenderId: '1061975495730',
    projectId: 'smartclass-35336',
    storageBucket: 'smartclass-35336.appspot.com',
    iosBundleId: 'com.example.smartclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdH_wn6ViCDAYPawuCH-jtJeeNsIAS5bY',
    appId: '1:1061975495730:ios:e1cf1a97a80994aa6e182b',
    messagingSenderId: '1061975495730',
    projectId: 'smartclass-35336',
    storageBucket: 'smartclass-35336.appspot.com',
    iosBundleId: 'com.example.smartclass.RunnerTests',
  );
}
